// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Tests real extracted submission scopes; does not claim to execute a D3D9 device.
void require(bool value, const char* message) {
  if (!value) { std::fprintf(stderr, "HOT_COMMAND_FAIL %s pid=%lu\n", message, GetCurrentProcessId()); std::exit(2); }
}
constexpr uint32_t deviceHandle = 0xc0dec0deu;
constexpr uint32_t sentinel = 0x6e6e6e6eu;
const Commands::D3D9Command opcodes[] = {
  Commands::IDirect3DDevice9Ex_SetRenderState, Commands::IDirect3DDevice9Ex_SetTextureStageState,
  Commands::IDirect3DDevice9Ex_SetSamplerState, Commands::IDirect3DDevice9Ex_DrawPrimitive,
  Commands::IDirect3DDevice9Ex_DrawIndexedPrimitive
};
const unsigned fieldCounts[] = {2, 3, 3, 3, 6};
size_t memorySize(size_t headers, size_t words) {
  return headers * sizeof(Header) + AtomicCircularQueue<Header, Accessor::Writer>::getExtraMemoryRequirements() + words * sizeof(uint32_t);
}
std::array<uint32_t, 6> values(unsigned api, uint32_t index) {
  const uint32_t edges[] = {0, 1, UINT32_MAX, 0x80000000u, 0x7fffffffu, 0xfffffffdu, 0xabcdef01u, 0x55555555u};
  std::array<uint32_t, 6> result {};
  for (unsigned i = 0; i < result.size(); ++i) { result[i] = edges[(index + i) % 8]; }
  // Keep enum values valid; exercise the whole DWORD range in ordinary fields.
  if (api == 0) { result[0] = D3DRS_ZENABLE; }
  if (api == 1) { result[1] = D3DTSS_COLOROP; }
  if (api == 2) { result[1] = D3DSAMP_ADDRESSU; }
  if (api >= 3) { result[0] = D3DPT_TRIANGLELIST; }
  return result;
}
#ifdef REMIX_BRIDGE_CLIENT
UID submit(unsigned api, const std::array<uint32_t, 6>& v) {
  HotSender sender;
  switch (api) {
    case 0: return sender.SetRenderState(static_cast<D3DRENDERSTATETYPE>(v[0]), v[1]);
    case 1: return sender.SetTextureStageState(v[0], static_cast<D3DTEXTURESTAGESTATETYPE>(v[1]), v[2]);
    case 2: return sender.SetSamplerState(v[0], static_cast<D3DSAMPLERSTATETYPE>(v[1]), v[2]);
    case 3: return sender.DrawPrimitive(static_cast<D3DPRIMITIVETYPE>(v[0]), v[1], v[2]);
    default: {
      INT signedBase = 0;
      static_assert(sizeof(signedBase) == sizeof(v[1]), "wire INT size");
      std::memcpy(&signedBase, &v[1], sizeof(signedBase));
      return sender.DrawIndexedPrimitive(static_cast<D3DPRIMITIVETYPE>(v[0]), signedBase, v[2], v[3], v[4], v[5]);
    }
  }
}
UID legacy(unsigned api, const std::array<uint32_t, 6>& v) {
  Device::Command command(opcodes[api], deviceHandle);
  const UID uid = command.get_uid();
  switch (api) {
    case 0: command.send_many(v[0], v[1]); break;
    case 1: case 2: case 3: command.send_many(v[0], v[1], v[2]); break;
    default: command.send_many(v[0], v[1], v[2], v[3], v[4], v[5]); break;
  }
  require(command.finish() == Result::Success, "legacy encoder commit");
  return uid;
}
struct Snapshot { Header header; uint64_t published; std::vector<uint32_t> data; };
Snapshot encode(bool packet, unsigned api, uint32_t index, size_t position, size_t capacity) {
  static unsigned channelSequence = 0;
  const std::string name = "HotWire" + std::to_string(channelSequence++);
  WriterChannel writer(name, memorySize(4, capacity), 4, capacity);
  ReaderChannel reader(name + "Reply", memorySize(4, capacity), 4, capacity);
  Device::install(&writer, &reader);
  require(writer.data->get_total_size() == capacity, "exact small ring capacity");
  std::fill(writer.data->data(), writer.data->data() + capacity, sentinel);
  // Public scalar writes establish a real ring cursor, then mark them consumed.
  for (size_t i = 0; i < position; ++i) { require(writer.data->push(sentinel) == Result::Success, "seed cursor"); }
  writer.control->published.store(position);
  writer.control->consumed.store(position);
  writer.cachedConsumed = position;
  const auto v = values(api, index);
  require((packet ? submit(api, v) : legacy(api, v)) == 0, "first UID unchanged");
  require(Device::healthy() && !writer.commands->isEmpty(), "destructor immediately publishes Header");
  Result result;
  const Header header = writer.commands->pull(result, 20);
  require(result == Result::Success && writer.commands->isEmpty(), "exactly one Header");
  require(header.command == opcodes[api] && header.pHandle == deviceHandle && header.flags == 0, "opcode handle flags");
  require(writer.control->published.load() == position + 1 + fieldCounts[api], "exact published frontier");
  require(header.dataOffset == (position + 1 + fieldCounts[api]) % capacity, "Header data end");
  require(writer.data->data()[position] == 0, "UID is first wire DWORD");
  for (unsigned i = 0; i < fieldCounts[api]; ++i) {
    require(writer.data->data()[(position + 1 + i) % capacity] == v[i], "exact independent wire field order");
  }
  return {header, writer.control->published.load(), {writer.data->data(), writer.data->data() + capacity}};
}
void wireCases() {
  unsigned cases = 0;
  for (const size_t capacity : {size_t(9), size_t(17)}) {
    for (size_t position = 0; position < capacity; ++position) {
      for (unsigned api = 0; api < 5; ++api) {
        for (uint32_t index = 0; index < 8; ++index) {
          const auto a = encode(false, api, index, position, capacity);
          const auto b = encode(true, api, index, position, capacity);
          require(a.header.command == b.header.command && a.header.flags == b.header.flags &&
            a.header.dataOffset == b.header.dataOffset && a.header.pHandle == b.header.pHandle &&
            a.published == b.published && a.data == b.data, "legacy/Packet byte equivalence including untouched storage");
          ++cases;
        }
      }
    }
  }
  std::printf("HOT_COMMAND_WIRE_PASS cases=%u negative_INT_and_wrap=1\n", cases);
}
void failureCase(unsigned api, bool headerFull) {
  GlobalOptions::timeout = 10; GlobalOptions::retries = 1;
  constexpr size_t capacity = 64;
  WriterChannel writer("HotFault", memorySize(4, capacity), 4, capacity);
  ReaderChannel reader("HotFaultReply", memorySize(4, capacity), 4, capacity);
  Device::install(&writer, &reader);
  std::fill(writer.data->data(), writer.data->data() + capacity, sentinel);
  const unsigned queued = headerFull ? 3 : 1;
  if (headerFull) {
    for (unsigned i = 0; i < queued; ++i) {
      require(writer.commands->push({Commands::Bridge_Response, 0, 0, i}, 20) == Result::Success, "prefill Header queue");
    }
  } else {
    Device::Command fill(Commands::Bridge_Response, 99);
    for (unsigned i = 0; i < capacity - 1; ++i) { fill.send_data(sentinel); }
    require(fill.finish() == Result::Success, "prefill complete Data Ring");
  }
  const auto before = writer.control->published.load();
  const std::vector<uint32_t> bytesBefore(writer.data->data(), writer.data->data() + capacity);
  submit(api, values(api, 3));
  require(writer.control->fault.load() == 1 && !Device::healthy(), "reservation/enqueue failure poisons IPC");
  if (!headerFull) {
    require(writer.control->published.load() == before &&
      std::equal(bytesBefore.begin(), bytesBefore.end(), writer.data->data()), "failed reservation leaves payload/frontier unchanged");
  }
  // Header failure can advance published, but must never expose the failed Header.
  for (unsigned i = 0; i < queued; ++i) {
    Result result;
    const auto header = writer.commands->pull(result, 20);
    require(result == Result::Success && header.command == Commands::Bridge_Response, "previous queued command remains intact");
  }
  require(writer.commands->isEmpty(), "failed hot command never queued");
  const auto failedFrontier = writer.control->published.load();
  const std::vector<uint32_t> failedBytes(writer.data->data(), writer.data->data() + capacity);
  submit((api + 1) % 5, values((api + 1) % 5, 4));
  require(writer.commands->isEmpty() && writer.control->published.load() == failedFrontier &&
    std::equal(failedBytes.begin(), failedBytes.end(), writer.data->data()), "sticky fault stops subsequent publication and writes");
  std::printf("HOT_COMMAND_FAULT_PASS api=%u mode=%s\n", api, headerFull ? "header-full" : "data-full");
}
#else
template<size_t N> void checkFields(const std::array<uint32_t, N>& actual, const std::array<uint32_t, 6>& expected) {
  for (size_t i = 0; i < N; ++i) { require(actual[i] == expected[i], "original Host scalar reader exact field value"); }
}
void readFields(unsigned api, const std::array<uint32_t, 6>& expected) {
  switch (api) {
    case 0: checkFields(read_SetRenderState(), expected); break;
    case 1: checkFields(read_SetTextureStageState(), expected); break;
    case 2: checkFields(read_SetSamplerState(), expected); break;
    case 3: checkFields(read_DrawPrimitive(), expected); break;
    default: checkFields(read_DrawIndexedPrimitive(), expected); break;
  }
}
#endif
void crossProcess(uint32_t count) {
  constexpr size_t capacity = 17;
#ifdef REMIX_BRIDGE_CLIENT
  WriterChannel writer("HotForward", memorySize(8, capacity), 8, capacity);
  ReaderChannel reader("HotReverse", memorySize(8, capacity), 8, capacity);
#else
  WriterChannel writer("HotReverse", memorySize(8, capacity), 8, capacity);
  ReaderChannel reader("HotForward", memorySize(8, capacity), 8, capacity);
#endif
  Device::install(&writer, &reader);
  for (uint32_t sequence = 0; sequence < count; ++sequence) {
    const unsigned api = sequence % 5;
    const auto v = values(api, sequence / 5);
#ifdef REMIX_BRIDGE_CLIENT
    require(submit(api, v) == sequence, "monotonic Client UID");
    require(Device::waitForCommand(Commands::Bridge_Response, 0, nullptr, true, sequence) == Result::Success, "immediate matching Host reply");
    require(Device::get_data() == sequence, "reply UID payload");
    Device::pop_front();
#else
    require(Device::waitForCommand() == Result::Success, "Host receives each immediate API submission");
    const auto h = Device::pop_front();
    require(h.command == opcodes[api] && h.pHandle == deviceHandle && h.flags == 0, "cross-process opcode handle flags");
    require(Device::get_data() == sequence, "Host scalar UID");
    readFields(api, v);
    Device::end_read_data();
    Device::Command reply(Commands::Bridge_Response, sequence);
    reply.send_data(sequence);
    require(reply.finish() == Result::Success, "Host ACK commit");
#endif
    require(Device::healthy(), "cross-process IPC remains healthy");
  }
  std::printf("HOT_COMMAND_CROSS_PASS bits=%u count=%u role=%s\n", unsigned(sizeof(void*) * 8), count,
#ifdef REMIX_BRIDGE_CLIENT
    "client"
#else
    "host"
#endif
  );
}
int wmain(int argc, wchar_t** argv) {
  require(argc >= 3, "GUID and mode required");
  require(gUniqueIdentifier.setGuid(&argv[1]), "unique session GUID");
  const std::wstring mode = argv[2];
#ifdef REMIX_BRIDGE_CLIENT
  if (mode == L"wire") { wireCases(); return 0; }
  if (mode == L"header-full" || mode == L"data-full") {
    require(argc == 4, "failure API required");
    const unsigned api = std::wcstoul(argv[3], nullptr, 10);
    require(api < 5, "valid API index");
    failureCase(api, mode == L"header-full"); return 0;
  }
#endif
  require(mode == L"cross" && argc == 4, "cross count required");
  const uint32_t count = std::wcstoul(argv[3], nullptr, 10);
  require(count >= 40 && count <= 100000, "bounded complete cross-process coverage");
  crossProcess(count);
  return 0;
}
