# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract five real Client submission scopes and original Host scalar readers.

Reuses the production IPC fixture; D3D9 calls/state validation are deliberately
outside this transport regression. No serializer is reimplemented in adapters.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

from generate_buffer_contract_test import method
from generate_ipc_transport_test import generate as generate_transport

ROOT = Path(__file__).resolve().parents[1]
APIS = ('SetRenderState', 'SetTextureStageState', 'SetSamplerState',
        'DrawPrimitive', 'DrawIndexedPrimitive')


def digest(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def generate(source, output):
    generate_transport(source, output)
    client_path = source / 'bridge/src/client/d3d9_device.cpp'
    host_path = source / 'bridge/src/server/main.cpp'
    client = client_path.read_text(encoding='utf-8')
    host = host_path.read_text(encoding='utf-8')
    wrappers = ['#include <d3d9.h>',
                'using Device = Bridge<BridgeId::Device>;',
                '#ifdef REMIX_BRIDGE_CLIENT',
                'using ClientMessage = Device::Command;',
                'struct HotSender {',
                '  uint32_t getId() const { return 0xc0dec0deu; }']
    metadata = {}
    host_wrappers = []
    for name in APIS:
        marker = 'HRESULT Direct3DDevice9Ex_LSS<EnableSync>::' + name + '('
        start, end = method(client, marker)
        body = client[start:end]
        signature = re.match(re.escape(marker) + r'([^)]*)\)', body).group(1)
        arguments = [arg.strip().rsplit(' ', 1)[1] for arg in signature.split(',')]
        opcode = 'Commands::IDirect3DDevice9Ex_' + name
        if body.count('ClientMessage c(' + opcode + ',') != 1:
            raise ValueError(name + ': expected exactly one submission')
        command = body.index('ClientMessage c(' + opcode + ',')
        opening = body.rfind('{', 0, command)
        depth, scope_end = 1, opening + 1
        while depth and scope_end < len(body):
            depth += (body[scope_end] == '{') - (body[scope_end] == '}')
            scope_end += 1
        if depth:
            raise ValueError(name + ': unclosed submission scope')
        scope = body[opening:scope_end]
        if not re.fullmatch(r'\{\s*ClientMessage c\([^;]+;\s*currentUID = c.get_uid\(\);\s*\}', scope):
            raise ValueError(name + ': unexpected submission scope; review extraction')
        if 'bridge_data::fields(' not in scope:
            raise ValueError(name + ': candidate must use Packet fields')
        wrappers += ['  UID ' + name + '(' + signature + ') {',
                     '    UID currentUID = 0;', scope, '    return currentUID;', '  }']
        host_marker = 'case IDirect3DDevice9Ex_' + name + ':'
        hs, he = method(host, host_marker)
        host_case = host[hs:he]
        pull_lines = re.findall(r'^\s*PULL(?:_[IUD])?\([^;]+;', host_case, re.M)
        if len(pull_lines) != len(arguments):
            raise ValueError(name + ': unexpected Host scalar reader')
        reader = '\n'.join(line.strip() for line in pull_lines)
        host_wrappers += ['std::array<uint32_t, ' + str(len(arguments)) + '> read_' + name + '() {',
                          reader, 'return {' + ', '.join('static_cast<uint32_t>(' + arg + ')' for arg in arguments) + '};', '}']
        metadata[name] = {'client_scope_sha256': digest(scope),
                          'host_scalar_reads_sha256': digest(reader),
                          'signature': signature, 'field_count': len(arguments)}
    wrappers += ['};', '#else', 'using DeviceBridge = Device;']
    for macro in ('PULL', 'PULL_I', 'PULL_U', 'PULL_D'):
        matches = re.findall(r'^#define ' + macro + r'\([^\n]+', host, re.M)
        if len(matches) != 1:
            raise ValueError('Expected one original Host macro: ' + macro)
        wrappers += matches
    wrappers += host_wrappers + ['#undef PULL', '#undef PULL_I', '#undef PULL_U', '#undef PULL_D', '#endif']
    (output / 'hot_command_submissions.h').write_text('\n'.join(wrappers) + '\n', encoding='utf-8')
    transport = output / 'ipc_transport.cpp'
    generated = transport.read_text(encoding='utf-8')
    original_include = '#include "ipc_transport_cases.cpp"'
    if generated.count(original_include) != 1:
        raise ValueError('Unexpected transport fixture include')
    transport.write_text(generated.replace(original_include,
        '#include "hot_command_submissions.h"\n#include "hot_command_packets_cases.cpp"'), encoding='utf-8')
    manifest_path = output / 'source-manifest.json'
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    manifest['source_sha256'].update({'client/d3d9_device.cpp': digest(client), 'server/main.cpp': digest(host)})
    manifest['hot_command_extractions'] = metadata
    manifest['adapters'] += ['five exact Client submission scopes in typed wrappers with fixed device handle',
                             'original Host scalar PULL macros and statements; D3D9 execution excluded']
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    parser.add_argument('--output', type=Path, default=ROOT / '.deps/hot-command-packets')
    args = parser.parse_args()
    generate(args.source.resolve(), args.output.resolve())
