# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Run bounded production hot-command regressions and preserve exit evidence."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import uuid

ROOT = Path(__file__).resolve().parents[1]


def run(directory, count=2000):
    receipt = {'count_per_host': count, 'executables': {}, 'tests': []}
    for role in ('client32', 'host32', 'host64'):
        exe = directory / ('hot-command-' + role + '.exe')
        receipt['executables'][role] = hashlib.sha256(exe.read_bytes()).hexdigest()

    def save():
        (directory / 'test-receipt.json').write_text(json.dumps(receipt, indent=2) + '\n', encoding='utf-8')

    def single(mode, api=None):
        args = [str(directory / 'hot-command-client32.exe'), str(uuid.uuid4()), mode]
        if api is not None:
            args.append(str(api))
        result = subprocess.run(args, capture_output=True, text=True, timeout=90)
        entry = {'mode': mode, 'api': api, 'exit': result.returncode,
                 'stdout': result.stdout, 'stderr': result.stderr}
        receipt['tests'].append(entry)
        print(result.stdout + result.stderr, end='', flush=True)
        save()
        if result.returncode:
            raise RuntimeError('Hot command regression failed: ' + mode)

    try:
        single('wire')
        for mode in ('header-full', 'data-full'):
            for api in range(5):
                single(mode, api)
        for role in ('host32', 'host64'):
            args = [str(uuid.uuid4()), 'cross', str(count)]
            processes = []
            try:
                for current in (role, 'client32'):
                    processes.append(subprocess.Popen([str(directory / ('hot-command-' + current + '.exe')), *args],
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True))
                client_output = processes[1].communicate(timeout=90)[0]
                host_output = processes[0].communicate(timeout=20)[0]
                entry = {'mode': 'cross', 'host_role': role, 'host_exit': processes[0].returncode,
                         'client_exit': processes[1].returncode, 'host_stdout': host_output, 'client_stdout': client_output}
                receipt['tests'].append(entry)
                print(client_output + host_output, end='', flush=True)
                save()
                if entry['host_exit'] or entry['client_exit']:
                    raise RuntimeError('Hot command cross-process regression failed: ' + role)
            finally:
                for process in processes:
                    if process.poll() is None:
                        process.kill()
                        process.wait()
        receipt['status'] = 'passed'
        print('HOT_COMMAND_ALL_PASS', flush=True)
    except Exception as error:
        receipt['status'] = 'failed'
        receipt['error'] = str(error)
        raise
    finally:
        save()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', type=Path, default=ROOT / '.deps/hot-command-packets')
    parser.add_argument('--count', type=int, default=2000)
    args = parser.parse_args()
    run(args.directory.resolve(), args.count)
