# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param(
  [ValidateSet('client32','host32','host64')][string]$CompileRole,
  [string]$Source,
  [string]$Output
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
if (-not $Source) { $Source = Join-Path $repoRoot '.deps/dxvk-remix' }
if (-not $Output) { $Output = Join-Path $repoRoot '.deps/hot-command-packets' }
$Source = [System.IO.Path]::GetFullPath($Source)
$Output = [System.IO.Path]::GetFullPath($Output)
if ($CompileRole) {
  $arch = if ($CompileRole -eq 'host64') { 'x64' } else { 'x86' }
  . (Join-Path $Source 'bridge/build_common.ps1')
  SetupVS -Platform $arch -VcVarsVer '14.29'
  Push-Location $Output
  try {
    $roleFlags = if ($CompileRole -eq 'host32') { @('/DREMIX_BRIDGE_X86_SERVER','/DREMIX_BRIDGE_SERVER') } else { @() }
    & cl.exe /nologo /std:c++17 /EHsc /O2 /W3 /DNDEBUG /DNOMINMAX /DWIN32 @roleFlags "/I$Output" "/I$repoRoot/tests" ipc_transport.cpp util_sharedmemory.cpp util_semaphore.cpp data_diagnostics.cpp exception_diagnostics.cpp "/Fe:hot-command-$CompileRole.exe" /link ole32.lib psapi.lib
    if ($LASTEXITCODE -ne 0) { throw "Hot command compilation failed: $CompileRole" }
  } finally { Pop-Location }
} else {
  python "$repoRoot/scripts/generate_hot_command_packets.py" --source $Source --output $Output
  if ($LASTEXITCODE -ne 0) { throw 'Hot command source extraction failed' }
  foreach ($role in @('client32','host32','host64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileRole $role -Source $Source -Output $Output
    if ($LASTEXITCODE -ne 0) { throw "Hot command compilation failed: $role" }
  }
  python "$repoRoot/scripts/run_hot_command_packets.py" --directory $Output
  if ($LASTEXITCODE -ne 0) { throw 'Hot command native regression failed' }
}
