# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Optional local MinGW validation. CI uses test_hot_command_packets.ps1/MSVC.

Example: python scripts/test_hot_command_packets_mingw.py
  --source results/ipc-hot-packets/source
  --output results/ipc-hot-packets/native
  --toolchain .deps/compact-tools/toolchain/w64devkit/bin

The generated fixture alone receives required MinGW syntax/CRT adapters.
Windows SEH recording is replaced by an explicit no-op observer; production
transport, fault handling, serializer and tested Client/Host scopes stay intact.
"""
import argparse
import concurrent.futures
import hashlib
import json
import os
from pathlib import Path
import subprocess

from generate_hot_command_packets import generate, ROOT
from run_hot_command_packets import run


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main(source, output, toolchain):
    generate(source, output)
    adaptations = {}

    def adapt(name, function):
        path = output / name
        before = path.read_text(encoding='utf-8')
        after = function(before)
        if before == after:
            raise ValueError('Expected MinGW adaptation no longer matches: ' + name)
        path.write_text(after, encoding='utf-8', newline='\n')
        adaptations[name] = {'before_utf8': hashlib.sha256(before.encode()).hexdigest(), 'after_sha256': sha(path)}

    adapt('ipc_transport.cpp', lambda s: s.replace('std::is_base_of<BridgeId::_Bridge, BRIDGE_ID>', 'std::is_base_of<::BridgeId::_Bridge, BRIDGE_ID>'))
    adapt('util_circularbuffer.h', lambda s: s.replace('using CircularQueue::', 'using CircularQueue<T>::')
          .replace('      CircularQueue(name,', '      CircularQueue<T>(name,')
          .replace('    using BaseType = T;', '    using BaseType = T;\n    using CircularQueue<T>::m_data;\n    using CircularQueue<T>::m_pos;\n    using CircularQueue<T>::m_size;\n    using CircularQueue<T>::m_name;'))
    adapt('util_circularqueue.h', lambda s: s.replace('std::exception("', 'std::runtime_error("'))
    adapt('util_guid.h', lambda s: s.replace('_snprintf_s(', 'std::snprintf('))
    (output / 'exception_observer_adapter.cpp').write_text('''#include "exception_diagnostics.h"
namespace bridge_exception {
CommandScope::CommandScope(Queue,uint16_t,uint32_t,const char*,bool,uint32_t) {}
CommandScope::~CommandScope() {}
void CommandScope::setUid(uint32_t) {}
void recordCommand(bool,Queue,uint16_t,uint32_t,bool,uint32_t) {}
}
''', encoding='utf-8')
    env = dict(os.environ, PATH=str(toolchain) + os.pathsep + os.environ['PATH'])

    def build(role):
        compiler = 'g++.exe' if role == 'host64' else 'i686-w64-mingw32-g++.exe'
        cmd = [str(toolchain / compiler), '-std=c++17', '-O2', '-pthread', '-static', '-municode',
               '-UUNICODE', '-U_UNICODE', '-DNOMINMAX', '-DWIN32', '-D_WIN32_WINNT=0x0601', '-DNDEBUG',
               '-include', 'stdexcept', '-include', 'sstream', '-include', 'cstring',
               '-I', str(output), '-I', str(ROOT / 'tests')]
        if role == 'host32':
            cmd += ['-DREMIX_BRIDGE_X86_SERVER', '-DREMIX_BRIDGE_SERVER']
        exe = output / ('hot-command-' + role + '.exe')
        cmd += ['ipc_transport.cpp', 'util_sharedmemory.cpp', 'util_semaphore.cpp', 'data_diagnostics.cpp',
                'exception_observer_adapter.cpp', '-lole32', '-lpsapi', '-o', str(exe)]
        result = subprocess.run(cmd, cwd=output, env=env, capture_output=True, text=True, timeout=180)
        (output / (role + '-build.log')).write_text(result.stdout + result.stderr, encoding='utf-8')
        print('HOT_COMMAND_BUILD', role, 'exit', result.returncode, flush=True)
        return {'role': role, 'command': cmd, 'exit': result.returncode,
                'executable_sha256': sha(exe) if result.returncode == 0 else None}

    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        builds = list(executor.map(build, ('client32', 'host32', 'host64')))
    receipt = {'source': str(source), 'mingw_portability_adaptations': adaptations, 'builds': builds,
               'observer_adapter': 'SEH exception recording only is disabled; actual IPC fault/read behavior is unchanged.',
               'fixture_sha256': {name: sha(ROOT / 'tests' / name) for name in
                    ('hot_command_packets_cases.cpp', 'ipc_transport_support.h', 'ipc_wait_injection.h')}}
    (output / 'build-receipt.json').write_text(json.dumps(receipt, indent=2) + '\n', encoding='utf-8')
    if any(item['exit'] for item in builds):
        raise RuntimeError('MinGW compilation failed; inspect per-role build logs')
    run(output)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    parser.add_argument('--output', type=Path, default=ROOT / '.deps/hot-command-packets-mingw')
    parser.add_argument('--toolchain', type=Path, default=ROOT / '.deps/compact-tools/toolchain/w64devkit/bin')
    args = parser.parse_args()
    main(args.source.resolve(), args.output.resolve(), args.toolchain.resolve())
